[package]
name = "waiter_codegen"
version = "1.0.0"

[dependencies]
waiter_core = { path = "../waiter_core" }
quote = "1.0.7"

[dependencies.syn]
version = "1.0.38"
features = [ "full" ]

[lib]
proc-macro = true
