[package]
name = "waiter_codegen"
version = "1.0.0"
description = "Macro for Waiter DI"
repository = "https://github.com/dmitryb-dev/waiter"
license = "MIT"
readme = "../../README.md"

[dependencies]
quote = "1.0.7"
regex = "1.3.9"

[dependencies.syn]
version = "1.0.38"
features = [ "full" ]

[lib]
proc-macro = true
