[package]
name = "waiter"
version = "1.0.0"
description = "Dependency injection"
repository = "https://github.com/dmitryb-dev/waiter"
license = "MIT"
readme = "README.md"

[workspace]
members = [ "crates/*" ]

[dependencies]
waiter_core = { path = "crates/waiter_core", version = "1.0.0" }
waiter_codegen = { path = "crates/waiter_codegen", version = "1.0.0" }
config = "0.9"