[package]
name = "waiter_di"
version = "1.1.1"
description = "Dependency injection"
keywords = [ "dependency-injection", "inversion-of-control", "di", "ioc"]
repository = "https://github.com/dmitryb-dev/waiter"
license = "MIT"
readme = "README.md"
authors = [ "dmitryb.dev@gmail.com" ]

[workspace]
members = [ "crates/*" ]

[dependencies]
waiter_codegen = { path = "crates/waiter_codegen", version = "1.1.2" }
config = "0.9"
regex = "1.3.9"